### ISSUE TITLE
Signature field digest name change

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#10]
Change the field `digest` to `signature` and change `signature` to `child_signature`.

Modify any existing code to appropriately handle the crawling/iteration through the child signatures.

The use of the name _digest_ was a misnomer as a digest is the hash of a message - in haste, we kept that name to avoid complexity in handling the child signatures.

**Comment by wolfpack94** [comment]
Completed this issue. All modified files are in branch: issue-10/Signature-Refactoring.
Went through all files and found instances of signature, changing some of them to child_signature and the same with digest to signature. Verified that the code works after making the modification.

**Comment by j0j0r0** [comment]
Cool. 
Put in a pull request and we'll close after review and merge.

**Comment by j0j0r0** [comment]
Merged PR #11
