### ISSUE TITLE
Node/network setup question 

### ISSUE THREAD

**Issue by albertma** [dragonchain/dragonchain#100]
I am trying to setup a node network in my office, but when I look into the code.
There is a  transactions = transaction_db.get_all(block_id=current_block_id), I always got null return value. It seems transaction will never be updated. I ran the script to post transaction information, and the transaction record in database has a new status and null block_id, how does the system to update the block_id, and synchronized block between nodes?

Thank you.

I would like to implement a blockchain on Android OS,  anyone can help me? Thank you

**Comment by albertma** [comment]
Any one can help me ?

**Comment by Voxelot** [comment]
Hey Albert, sorry you're having issues. I'm thinking your problem relates to the way we fixate the block id's for transactions. Currently, transactions only get assigned to a block if they were submitted while the processing node was running. I believe this is an issue that needs to be addressed and wrote up an issue here #101. We'll get on this soon.

**Comment by albertma** [comment]
Thanks @Voxelot , I setup nodes network under phase 3, but I did not get block id either. I think maybe I misoperate the system.
But I follow your docker, it is only one command. 

Could you please tell me, how to setup a private nodes-network, so that I can observe synchronizing data among nodes?

Thank you for your time and patience.

**Comment by Voxelot** [comment]
Do you have any nodes running phase 1? Only phase 1 nodes will assign block ids.

**Comment by j0j0r0** [comment]
A question for you Albert, are you intending to use an Android mobile app as a client to interact with the blockchain, or are you intending to run the "blockchain on Android"? 

Though running a node directly  on a mobile device is possible, it is not supported at this time.

**Comment by albertma** [comment]
I am trying to translate the python implementation into java implementation.

**Comment by j0j0r0** [comment]
Ah, OK - hmm.

It may be best for you to start with a reading of the [Architecture Document](https://dragonchain.github.io/architecture).

We're working on a few things that will allow multiple language smart contracts (Java is on the list).
But, if you're wanting the node to actually be running in Java that probably won't help you completely.

What part of the Python implementation is confusing to you?

**Comment by TheRoboKitten** [comment]
Same error: ERROR:apscheduler.executors.default:Job "trigger_handler (trigger: cron[second='*/5'], next run at: 2017-11-18 21:02:40 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "processing.py", line 163, in trigger_handler
    self.notify(event_name=1, current_block_id=get_current_block_id())
  File "processing.py", line 126, in notify
    observer["callback"](config=observer["config"], **kwargs)
  File "processing.py", line 319, in _execute_phase_1
    self.network.public_broadcast(block_info, phase)
  File "/opt/dragonchain/blockchain/network.py", line 712, in public_broadcast
    for node in self.peer_dict[PHASE_5_NODE]:


Imported nodes

node phase 4 01111

**Comment by cheeseandcereal** [comment]
stale
