### ISSUE TITLE
Block Fixation

### ISSUE THREAD

**Issue by Voxelot** [dragonchain/dragonchain#101]
To build blocks, the processing node will run a query every 5 seconds to retrieve the last 5 seconds of blocks. The issue is that transactions inserted more than 5 seconds before the processing node has started don't get picked up and fixated into a block, leaving them with a null block id forever.

The central question we need to answer is whether we want all unassigned transactions older than 5 seconds to be included in the current block, or if we wish to map them to potentially old block ids based on when they were submitted (create_ts/5).

Depending on how long the node was down for there could be an overwhelming amount of transactions either in the first block after boot, or too many blocks if we do a create_ts/5. The simplest option may be to configure an upper limit to the number of transactions in a block. This way if say thousands of records were submitted while the processing node was down, it would amortize the network bandwidth required to get them signed by capping the volume of transactions sent every five seconds while prioritizing the oldest records (first in). 

This will primarily involve a refactoring of the transaction_db's [fixate block method](https://github.com/dragonchain/dragonchain/commit/af01fba302ff96bf2c9dd437e883b7b5610cfb52#diff-8b8fb2fbf1e99e72cf7f394d6e34664fR191) to paginate in order by oldest create_ts and limit by the transactions per block limit.

**Comment by j0j0r0** [comment]
I think (on first glance) that yes, we should put all non-assigned transactions (that are approved) into the current block (not old block IDs). 

Maybe allow configuration of maximum transaction count in a block with a default? 

Then yes, page through all new and unassigned transactions approving and accepting up to the max for the block.

**Comment by cheeseandcereal** [comment]
stale
