### ISSUE TITLE
Integer Block IDs

### ISSUE THREAD

**Issue by Voxelot** [dragonchain/dragonchain#102]
Currently, block id's are integers in the transactions table. The max positive value an integer can store is `2^31` but the current time is about `1489049092`. Since we have 5-second blocks, this means that we'll run out of block IDs in ~293 years (`(2^31 - 1489049092 / 5) * 5 seconds to years`). Should we up the block id to long?

**Comment by j0j0r0** [comment]
Yes, let's. 
We will address the y2.31k issue early.

**Comment by cheeseandcereal** [comment]
stale
