### ISSUE TITLE
Upgrade to Python 3.6

### ISSUE THREAD

**Issue by Voxelot** [dragonchain/dragonchain#103]
The project is currently only running under Python 2.7. By upgrading to 3.6 we'll gain several enhancements such as asyncio. This could boost performance when managing several connections simultaneously.

See an example of asyncio in use here: https://github.com/facebook/fbthrift/blob/master/thrift/tutorial/py.asyncio/PythonClient.py

**Comment by j0j0r0** [comment]
There was a [short discussion in Slack about this](https://dragonchain.slack.com/archives/general/p1486571591000305) - I would fully support though not top priority.

Maybe this could be a "project" and we could look for support to implement in future?

**Comment by cheeseandcereal** [comment]
stale
