### ISSUE TITLE
Scala Smart Contracts

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#109]
Create a Scala language SC implementation.
A module/package/class should be created which would allow the registration of any type of smart contract (see below) written in Scala.

_For details on existing smart contract (SC) implementation, see issue #99._

#### Transaction SC (TSC)

Transaction approve/deny business logic implementation

_Input: Accepts single Transaction JSON._
_Output: Responds with T/F approve/deny response_

#### Subscription SC (SSC)

Business logic to process Transactions and Verification Records arriving inbound from subscription data feeds (from other nodes). See #86 for information on structure.

_Input: JSON bundle with combination of Transactions and Verification Records_
_Output: None_

#### Library SC (LSC)

Generic or reusable SC code. Callable by any SC or core code. May be used for common module implementations such as currency or marketplace.

_Input: Arbitrary (this implementation may define limitations, e.g. string or JSON only)._
_Output: None_

#### Broadcast Receipt SC (BSC)

Business logic to process Verification Records coming back from upper nodes (higher level verification in network). This Verification Records are verifications/signings of higher nodes that were broadcast this node's VR/blocks.

_Input: Verification Record(s)_
_Output: None_

### Integration

Consider integration of the Scala SC module
Assume backend process running Scala communicating via I/O stream or RPC.

Options:

- I/O Stream
- RPC
- Script/stdio

#### References

- [Calling Scala from Python](http://stackoverflow.com/questions/39530375/how-to-call-scala-from-python)
- [Python/Scala Interop](http://chariotsolutions.com/presentation/polyglot-programming-with-python-pythonscala-interop/)
- Reach out to @micylt or @j0j0r0 for information on existing SC implementation

**Comment by Voxelot** [comment]
Due to java/scala warm-up times, it would probably make the most sense to deploy the scala code as a microservice alongside the python containers and then create python smart contracts that invoke HTTP APIs hosted by the Scala service. I see benefits to creating a Scala SDK with typed classes and APIs for interacting with verification records, transactions, and calling txn service apis though.

**Comment by cheeseandcereal** [comment]
stale
