### ISSUE TITLE
Current implementation for docker does not enable port overrides

### ISSUE THREAD

**Issue by steowens** [dragonchain/dragonchain#110]
The current implementation either doesn't have or doesn't document a way for the docker compose process for bootstrapping to override ports.  If you have a system running a service on 8080, 80 or 5432, then docker compose will fail due to address already in use issues.

**Comment by Voxelot** [comment]
Hey Steve, you can override the ports the containers bind to on the host OS by using the -p command (eg. `docker run -p 5555:5432 {postgrescontainerid}`. These are easily configurable by making your own copy of the [docker-compose.yml](https://github.com/dragonchain/dragonchain/blob/master/docker/docker-compose.yml) file and name it as somthing like custom-steve-compose.yml (or anything custom-*-compose.yml is gitignored). Using custom compose files is our current standard development process for creating arbitrary network topologies with multiple processing nodes and dbs running on custom defined ports. Let me know if you run into any issues!
