### ISSUE TITLE
Docker-Compose - Implement health checks to make services wait for DB to fully startup

### ISSUE THREAD

**Issue by Voxelot** [dragonchain/dragonchain#111]
In the [docker-compose](https://github.com/dragonchain/dragonchain/blob/master/docker/docker-compose.yml) example config, we're using [depends_on](https://docs.docker.com/compose/compose-file/compose-file-v2/#dependson) to startup postgres first before running the other services. However, if postgres isn't fully ready but the container is already "started", compose will attempt to start the other services and they'll fail due to connection issues.

By implementing the [healthcheck](https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck) against the db container (e.g. telnet to db:5432) we can ensure the db is fully started before initializing any other services.

**Comment by hagitarowe** [comment]
As noted by @Voxelot, there seems to be a race condition between the startup of the DB container and the Service containers. Services can successfully be started individually after confirming DB container is Running under Kitematic.

Error is as follows:
`Traceback (most recent call last):
  File "transaction_svc.py", line 44, in <module>
    from db.postgres import postgres
  File "/opt/dragonchain/blockchain/db/postgres/postgres.py", line 77, in <module>
    password=password)
  File "/usr/lib64/python2.7/site-packages/psycopg2/pool.py", line 156, in __init__
    self, minconn, maxconn, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/psycopg2/pool.py", line 58, in __init__
    self._connect()
  File "/usr/lib64/python2.7/site-packages/psycopg2/pool.py", line 62, in _connect
    conn = psycopg2.connect(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: Connection refused
Is the server running on host "db" (172.18.0.2) and accepting
TCP/IP connections on port 5432?`

**Comment by cheeseandcereal** [comment]
stale
