### ISSUE TITLE
Smart Contract (SC) load highest version

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#116]
Load highest version SC on load.
`FIXME` in `load_scs()` function - does it apply to other SC types?

See line 208 in `.../blockchain/smart_contracts/sc_trusted.py` -- https://github.com/dragonchain/dragonchain/blob/issue-99/smart-contracts/blockchain/smart_contracts/sc_trusted.py#L208

```
    # FIXME: only load highest version sc to avoid overwriting
    def load_scs(self):

```

**Comment by cheeseandcereal** [comment]
stale
