### ISSUE TITLE
Transaction Service bugs

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#123]
- Empty transaction type causes HTTP 500 response.
- Arbitrary transaction is silently rejected (client receives HTTP 201 - created, but transaction is stored with state "rejected"

Need to consider more rigorous testing...

**Comment by j0j0r0** [comment]
Apparently also not storing value for some fields in the transaction header:

- `family_of_business`
- `line_of_business`

**Comment by cheeseandcereal** [comment]
stale
