### ISSUE TITLE
how do i get started with transactions?

### ISSUE THREAD

**Issue by kedall** [dragonchain/dragonchain#133]
hi folks, 
 the docker compose works like a charm - but after that - i see no path to use the service.

 I am happy to help with the documentation if its needed - could someone give me some high level pointers on how to use this?

**Comment by mikehatch** [comment]
Seconded.  I'm still trying to figure out how to use the services...  also posted in the slack #support channel, awaiting response.

**Comment by roberte3** [comment]
I've written a set of blog entries that answer that  at this location: https://github.com/roberte3/Dragonblog 

Please take a look and let me know, if you have any questions.

**Comment by cheeseandcereal** [comment]
stale
