### ISSUE TITLE
Restrict curves to secp256k1

### ISSUE THREAD

**Issue by Voxelot** [dragonchain/dragonchain#135]
In order to ease interop with other [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Specification_Key_derivation) based networks and signing devices, we'll need to enforce the use of secp256k1.

- Update openSSL readme keygen examples to use bip39/bip32 instead
- Update the docker-compose bootstrap scripts to use secp256k1
- Validate configured curves using [from_string](https://github.com/warner/python-ecdsa/blob/6c8a70eb615d4cb85e37e8e054db910e8c62a5c6/src/ecdsa/keys.py#L153)

**Comment by cheeseandcereal** [comment]
stale
