### ISSUE TITLE
Hello, I would like to implement dragonchain.

### ISSUE THREAD

**Issue by TheRoboKitten** [dragonchain/dragonchain#136]
Hello, I am currently a developer for a trade bot called Zenbot.

I am faced with a dilema, trade and market simulations take large amounts of processing power.

How can I go about decentralizing nodejs using dragonchain. Since nodejs is single-threaded, it has to be run outside of nodejs for parallelization.
In short, what I want to do:
Send commands to blockchain.
Clients receive commands (one at a time preferably/scheduled)
Clients run commands through regular shell or nodejs execution.
Clients return HTML data to master.
Master/user who ran the simulation has the HTML generated on their machine and parsed into document.
I've spent all night looking for something along these lines. I just want to drop some github repository into ours and load-and-go and just run this in the background so that users can contribute with each other to run their market strategy simulations.

It should be so simple......
To me, this should function like having a pool security key and name, and you're good to go and run nodejs on a large cluster that some strategies would require to ever be profitable. For example, I developed a neural strategy and a signaling algorithm, but it has so many variables, it would take months to run on a 32-core opteron to find anything profitable.

Thanks 👍

**Comment by roberte3** [comment]
@Gr1dd 

Hey looking at the GitHub issues, looks like you ran into some issues with trying to make Dragonchain something it isn't.

I'd love to talk with you about what your trying to build, feel free to reach out to me. (My email is on googles platform, with my GitHub id as the address.)
