### ISSUE TITLE
Better Error Handling when Posting Transactions

### ISSUE THREAD

**Issue by roberte3** [dragonchain/dragonchain#140]
Currently when posting a transaction to Dragonchain, if there is an error with the transaction format, at best you get an error message returned that says, "{"error": {"type": "invalid input", "details": "ERROR:  Failed to parse JSON\n"}}" 

When posting a transaction with a malformed header, such as missing the "create_ts", you get an error message that says "{"error": {"type": "validation", "details": "'create_ts'"}}

When posting atransaction with multiple errors in you get a response error message of "    raise TypeError("Expected None, got %r" % result)" 

I'd like to have better error messages when posting transactions. 
For example, when posting and there are problems, return the rather undocumented format for transactions.

**Comment by Voxelot** [comment]
thanks, merged #147 

Let's cover APIs separately.
