### ISSUE TITLE
A small idea.

### ISSUE THREAD

**Issue by ghost** [dragonchain/dragonchain#152]
Hello,
I'm not sure if you guys have contact with bittrex over there, but the guys at zenbot are having trouble coding in their API because it doesn't support the order info to cancel an order.

This gave me a small idea,
Perhaps, you could sell a blockchain backend to bittrex, this way every order gets a verified hash and key, and every order gets blockchained. You could throw other hashed variables into the hash function on local client such as hardware information, uuids, mac addresses etc to protect their exchange.

In an ideal exchange, you'd have something like client order -> hashed -> key -> encrypted -> exchange -> key -> decrypted -> verified -> blockchained -> blockchain status OK returned.

There's no not verifying the orders were legitimately made in this scenario by the party who made the order. Atleast you would have a decryptable hash of the hardware information, mac addresses, model names and etc hashed into the block and encrypted instead of the way the transactions are currently verified by simple API keys and secrets. I feel like this data length of API keys and API secrets is too short, and even possibly brute-forcable. Remember, usernames are more important than passwords. Removing a username from the scenario and placing down an encryption key instead with hashed/encrypted information with padding aes data actually strengthens the protocol security between the client and the server. Especially over HTTPS APIs.

Anyway, 
HTTPS is weak. JSON is nice and all when it works. Websockets (atleast I dont think) is not an encrypted protocol, its just a nonce + secret + key (very short ones at that.)

Exchanges need to be better secured in this scenario, and I think this would fit well. I personally, think dragonchain could run one of the leading exchanges to coinbase. If that's in your bag at all.

**Comment by cheeseandcereal** [comment]
stale
