### ISSUE TITLE
Reconnection to node failure 

### ISSUE THREAD

**Issue by roberte3** [dragonchain/dragonchain#153]
Issue from the DragonChain Dev feed: User Samuel Navarro 
>>currently if there has been a connection attempt to a node that failed, the node doesnt attempt to >>connect again., Shouldnt this be something like continue verifying the node until X failed attempts? >>imnot even sure how it works on other p2p operations. I cant connect to that node again unless I >>restart the container

Looking at network.py my guess its an issue with refresh_registered(self) we don't have a fallback mechanism other than to toss an exception to the log handler when a connection fails.

**Comment by cheeseandcereal** [comment]
stale
