### ISSUE TITLE
Smart contracts are not loaded if one contract fails.

### ISSUE THREAD

**Issue by snavarro89** [dragonchain/dragonchain#154]
When loading the smart contracts from the database, if there is a smart contract that fails to execute (for some reason yet to be researched, when deploying there is no error, but when loading there is when using encoding) the other smart contracts are not executed, this is because the try..catch exception surrounds the for loop that iterates the smart contracts. To fix this we only need to either move the try catch inside the for loop, or add a new try..catch inside the for loop. This would be on smart_contracts.py function load_scs

**Comment by cheeseandcereal** [comment]
stale
