### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by liderako** [dragonchain/dragonchain#158]
I can do project with tokens at the platform dragonchain?

**Comment by roberte3** [comment]
What do you mean by tokens? 

Are you referring to Dragon tokens from the ICO or are you talking about issuing tokens with the open source dragonchain software?

**Comment by liderako** [comment]
I mean tokens from the ICO ( Example: EOS, etc at the ERC20)

**Comment by roberte3** [comment]
The plan is for the ERC20 DRGN tokens from the ICO to unlock features in the commercial version. 

At the date of this writing they are disconnected from the code on GitHub. 
Closing ticket.
