### ISSUE TITLE
python setup.py egg_info" failed with error

### ISSUE THREAD

**Issue by zhuimengshaonian66** [dragonchain/dragonchain#167]
hello everyone , when i do docker-compose  up -d    :
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-f_oeAm/merkle-proofs/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-f_oeAm/merkle-proofs/
ERROR: Service 'query_svc' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
       i cant solve it anyway,can you help me ?

**Comment by emtesenair** [comment]
Did you have a solution zhuimengshaonian66 ?

**Comment by emtesenair** [comment]
Resolved issue by setting pip version to 9.0.03 for below files:

- Processor_DockerFile
- Query_DockerFile
- Trasaction_Dockerfile

**Comment by Briechenstein12** [comment]
Command "python setup.py egg

    Collecting MySQL-Python
  Downloading MySQL-python-1.2.5.zip (108kB) 100%
     112kB 561kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-Ue6URf/MySQL-Python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 53, in get_config
        libraries = [ dequote(i[2:]) for i in libs if i.startswith(compiler_flag("l")) ]
      File "setup_posix.py", line 8, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range

**Comment by evrardjp** [comment]
Because dragonchain's setup.py is relying on setuptools [1] for its packaging, we should probably add setuptools and pip in its requirements.txt (with at least a minimum required version).

What do you think?

[1]: https://github.com/dragonchain/dragonchain/blob/2a2a6a02f3a2ea79b2420a72f49671db1f1ba760/setup.py#L32-L34

**Comment by aprilsnows** [comment]
Sounds like a good plan.
