### ISSUE TITLE
Proof of Work Implementation

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#27]
Implement generic PoW functionality.
Speak to John Roets for PoW design with fixed length blocks.
Interface should allow passage of difficulty level as parameter.

**Comment by j0j0r0** [comment]
We will then allow configuration of Proof (generic) and use of PoW for any given node/phase.
Will be integrated as a daemon feeding into the block or verification record creation.

**Comment by j0j0r0** [comment]
Need an abstract definition of both the Proof functionality itself and the artifact container which will be hashed.
Lucas Ontivero is going to write up ideas for the worker which will implement the Proof of Work, and I will write up thoughts on the container structure.

**Comment by j0j0r0** [comment]
There is a PR available for review and discussion - need to transfer.

**Comment by lontivero** [comment]
I transferred it in the PR https://github.com/dragonchain/dragonchain/pull/41
