### ISSUE TITLE
query criteria

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#28]
Add owner (and other fields) field to the query service criteria.
Add ability to query JSON payload.

**Comment by j0j0r0** [comment]
Add query capability for all transaction fields not already implemented.

For timestamp (`create_ts` and `transaction_ts`) fields, use the following encoding:

1. For range, translate integer dash integer as inclusive range, e.g. `120987-129089` should translate to `timestamp >= 120987 AND timestamp <= 120989`
1. For older than, use dash integer e.g. -120987 should translate to `timestamp <= 120987`
1. For newer than, use `integer` `dash` e.g. `-120987` should translate to `timestamp >= 120987`
1. For no range query, use `integer` e.g. `120987` should translate to `timestamp = 120987`

All ranges should result in inclusive queries.

**Comment by j0j0r0** [comment]
We should split the JSON query task into another ticket.

**Comment by wolfpack94** [comment]
Has already been merged. Closing issue.
