### ISSUE TITLE
Github Webhook Transaction Service

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#31]
Create a simple service endpoint to accept any JSON payload and create a valid blockchain transaction (adding header and signature structures).

To facilitate integration of simple calls like [Github web hooks|https://developer.github.com/enterprise/2.2/webhooks/], wherein Github will send an unalterable payload that we will want to place into a standard transaction and place on the blockchain.

We will likely need to allow configuration of transaction type, other header data, and signing key based upon HTTP headers contained in the request.

**Comment by roberte3** [comment]
Mind assigning this to me?
