### ISSUE TITLE
Containerization Orchestration

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#32]
Create script or other to allow user to bring up a node in one shot.

**Comment by j0j0r0** [comment]
Is this considered complete with the docker and docker compose merge?

**Comment by Voxelot** [comment]
I'd say so, the compose file will bring up a full dragonchain stack in one shot.

We may need additional tasks later on for handling CI deployments etc.

**Comment by wolfpack94** [comment]
@Voxelot Can this be closed?

**Comment by Voxelot** [comment]
Yeah I'll close it, any additional work on this will be broken out into separate tasks.
