### ISSUE TITLE
Isolate thrift dependencies

### ISSUE THREAD

**Issue by Voxelot** [dragonchain/dragonchain#34]
All logic relating to thrift should be self-contained in the networking modules.

Currently, there are calls to convert thrift data structures (thrift_transaction_to_dict and thrift_record_to_dict) into native python structures within processing.py (see https://github.com/dragonchain/dragonchain/blob/master/blockchain/processing.py#L300).

Thrift datatypes should be sanitized and converted in network.py, before being passed to the processing module. This makes the processing module interfaces simpler to reason about and improves maintainability if thrift is replaced later on.

**Comment by micylt** [comment]
So essentially at this point https://github.com/dragonchain/dragonchain/blob/master/blockchain/network.py#L521
phase_1 should be passed in as some python structure rather than a Thrift struct.

**Comment by Voxelot** [comment]
Exactly. I haven't looked at the conversion logic yet, but for phase 2 we might need to convert both the transactions and the record before passing the data to phase 2 processing.

**Comment by j0j0r0** [comment]
I would suppose that both input and output of `processing.py` module should be generic python/dict, and all conversions in both directions should be happening w/in `network.py` module.

Is that what we're saying?

And, can this be done at the top level of what is currently passed (e.g. using `thrift_record_to_dict`)?

**Comment by micylt** [comment]
I believe the output of processing.py is already being converted in network.

**Comment by Voxelot** [comment]
Completed by #40
