### ISSUE TITLE
Use constants for message data structures

### ISSUE THREAD

**Issue by Voxelot** [dragonchain/dragonchain#42]
There are currently a lot of dictionary structures being passed between the processing and network modules and the fields are being accessed via in place string literals. These should be replaced with constants to make refactoring easier and reduce potential bugs.

**Comment by cyR3X** [comment]
I'll take a crack at this one if you would like...

**Comment by micylt** [comment]
@cyR3X Absolutely. I added several global variables for some of the commonly used string literals, but there's still strings that should be global. Thank you.

**Comment by cyR3X** [comment]
@micylt What are your thoughts on me adding a "constants.py" file to hold all of the constants/variables for the project?  It would need to be imported (either completely or partially) into each existing file, but long-term might be a good idea...  Please let me know your thoughts.

**Comment by micylt** [comment]
@cyR3X That sounds like a good idea to me. We would obviously have to make sure the constants module is being included where it needs to be. Write something up if you'd like and we'll review it :). Let me know if you have anymore questions.

**Comment by cyR3X** [comment]
@micylt I have made some changes, but cannot push them to the "Master" branch from my local repo...  Can you (or someone else) add me as a contributor?  Thank you.
