### ISSUE TITLE
python setup.py gen_thrift

### ISSUE THREAD

**Issue by waterem** [dragonchain/dragonchain#59]
[root@localhost dragonchain]# python setup.py gen_thrift
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'gen_thrift'

**Comment by Voxelot** [comment]
Is thrift included in your path variable? Please use our [#support](https://dragonchain.slack.com/messages/support/) channel in [slack](https://dragonchain-slack.herokuapp.com/) for further assistance.
