### ISSUE TITLE
psql -U blocky -d blockchain -a -f depl.sql error

### ISSUE THREAD

**Issue by waterem** [dragonchain/dragonchain#60]
connection_attempts INT,
    /* connection latency */
    latency INT
);
psql:net.sql:97: ERROR:  syntax error at or near "NOT"
LINE 2: CREATE TABLE IF NOT EXISTS nodes (
                        ^
COMMIT;
ROLLBACK
BEGIN;
BEGIN
GRANT ALL ON nodes to blocky;
psql:net.sql:101: ERROR:  relation "nodes" does not exist
COMMIT;
ROLLBACK
[postgres@localhost sql]$
[postgres@localhost sql]$ psql -U blocky -d blockchain -a -f depl.sql^C

**Comment by Voxelot** [comment]
Unable to repro, please use our [#support](https://dragonchain.slack.com/messages/support/) channel for further assistance.
