### ISSUE TITLE
blockchain module problem?

### ISSUE THREAD

**Issue by waterem** [dragonchain/dragonchain#61]
[root@localhost postgres]# python /home/postgres/dragonchain/blockchain/transaction_svc.py --private-key /home/postgres/dragonchain/sk.pem --public-key /home/postgres/dragonchain/pk.pem
Traceback (most recent call last):
  File "/home/postgres/dragonchain/blockchain/transaction_svc.py", line 44, in <module>
    from blockchain.util.crypto import sign_transaction, valid_transaction_sig
ImportError: No module named blockchain.util.crypto

[root@localhost postgres]# ls
dragonchain
[root@localhost postgres]# ls dragonchain/blockchain/util/
crypto.py  __init__.py  insert_db.py  thrift_conversions.py

anybody know this why?

**Comment by j0j0r0** [comment]
Have you attempted again with the new docker container(s)?

**Comment by j0j0r0** [comment]
@micylt Have you had a chance to see this?

**Comment by micylt** [comment]
Perhaps this is a python path issue?

**Comment by j0j0r0** [comment]
That is what it looks like.

@waterem Did you try this with the Docker container (instructions in README), or have you approached as a PYTHONPATH issue?

See:
http://stackoverflow.com/questions/9320305/how-to-fix-the-python-path
http://stackoverflow.com/questions/33549546/python-path-issue

**Comment by j0j0r0** [comment]
Didn't realize issue was from NOV with no response - closing - @waterem if you still need help, please do reach out.

Thank you.
