### ISSUE TITLE
gen_thrift error message does not indicate missing Thrift compiler as root cause.

### ISSUE THREAD

**Issue by cnauroth** [dragonchain/dragonchain#80]
README.md documents that a developer can run this command to re-generate the Thrift compiled classes if the Thrift compiler is installed.

`python setup.py gen_thrift`

If the Thrift compiler is not installed, then the developer will see an error like this:

```
> python setup.py gen_thrift
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'gen_thrift'
```

Unfortunately, the error message doesn't indicate the real root cause: the missing Thrift compiler.  Instead, the message makes it look like the developer called the command incorrectly.  We can improve this by providing a more specific error message.

**Comment by j0j0r0** [comment]
Merged earlier PR #81
