### ISSUE TITLE
Automate thrift generation via shell script

### ISSUE THREAD

**Issue by wolfpack94** [dragonchain/dragonchain#84]
Write a shell script in order to generate the thrift files, copy the select ones into the blockchain/gen folder and delete the gen-py folder from the thrift directory.

**Comment by Voxelot** [comment]
Is this really necessary? Don't we already have a way to do this in [setup.py](https://github.com/dragonchain/dragonchain/blob/master/setup.py#L60)?

**Comment by wolfpack94** [comment]
Yes you are correct, running that will do the same but when running the command: thrift -r --gen py ../thrift/messaging.thrift you do not need all the files it generates and so this script only copies over what is necessary (i.e. ttypes.py, BlockchainService.py, BlockchainService-remote. when running the command above, you have to manually copy over the recreated files. It might not be needed, just thought it would be quicker.
