### ISSUE TITLE
Setup and execution improvements.

### ISSUE THREAD

**Issue by cnauroth** [dragonchain/dragonchain#88]
I'd like to propose several small changes to help new contributors get setup and executing the code.

* For Emacs users, set up .gitignore to ignore Emacs automatic backup files.
* Document a warning that the signing key must be kept private, and that we have set up .gitignore to prevent accidentally committing them to source control.
* As of pull request #77 , it is required to have a logs directory before running processing.py.  Previously, there was a call to `logging.basicConfig()` in crypto.py that would have done basic bootstrapping for logging without requiring the directory to exist, but that line has been removed.  Document that the directory must be created.
* Add shebang lines to call the Python interpreter to save a bit of typing during execution.

**Comment by j0j0r0** [comment]
Merged as #89
