### ISSUE TITLE
POST transaction giving 405 Method not found error

### ISSUE THREAD

**Issue by emtech2020** [dragonchain/dragonchain#91]
Hello - we started the transaction, query and processing services.  When we try to POST a transaction using the WebAPI we get a Method not found error... curl command we ran is:
curl -X POST -d @dragonchain_POST.txt http://localhost:8080/transaction --header "Content-Type:application/json"

the file (i.e. dragon chain_POST.txt includes elements that are depicted in the POST transaction on the Wiki page, i.e. something similar to this:
{
  "header": {
    "create_ts": 1432238220,
    "business_unit": "",
    "family_of_business": "",
    "line_of_business": "",
    "owner": "Marketplace",
    "transaction_type": "new",
    "actor": "SWID",
    "entity": "FORM_ID"
  },
  "payload": {
    "swid": "",
    "action":"created",
    "form_id":""
  }
}
)

**Comment by micylt** [comment]
Hi @emtech2020. Have you tried posting a transaction this way?
`curl -H 'Accept-Encoding: gzip,deflate' -X POST http://localhost:8000/transaction -d @dragonchain_POST.txt`

e.g.
https://github.com/dragonchain/dragonchain/blob/master/scripts/post_txn.sh#L2

Also, do take a look at the way we are currently structuring a transaction here.
https://github.com/dragonchain/dragonchain/blob/master/scripts/valid_payload.json

**Comment by emtech2020** [comment]
Thanks.. All set...
