### ISSUE TITLE
Network Setup

### ISSUE THREAD

**Issue by emtech2020** [dragonchain/dragonchain#92]
Overview of the scenario:
Started phase 1 (works fine):
> python processing.py --private-key ../pki/sk.pem --public-key ../pki/pk.pem --port 8081 --phase 1
>> initializing network
>> Phase 1 Verify Start.
>> Time bounds: 1485539840 - 1485539845 ...

Started phase 2 (gets stuck at 'initializing network'):
> python processing.py --private-key ../pki/sk.pem --public-key ../pki/pk.pem --port 8082 --phase 2
>> initializing network

Config file (default config, configs/blockchain.yml):

> node_id: 31ce807a-868c-11e6-99f6-3c970e3bee11
> owner: OWNER
> business: BUSINESS
> deploy_location: SEATTLE
> 
> public_transmission: 
>     p1_pub_trans: off
>     p2_pub_trans: off
>     p3_pub_trans: off
>     p4_pub_trans: off
> 
> receipt_request_time: 600
> 
> peers:
>     - localhost:8081:8f0aabca-aa2e-4aab-a1d2-8420ffba0cce:00010
>     - localhost:8082:0318edaf-4a08-49c9-ba03-c4d732fd8d9c:00011
>     - localhost:8083:f9aba210-1d66-4d06-80d6-e87895c8da00:00010
>     - localhost:8084:4cc5d599-df17-4c4a-8f3c-2ce70f874c54:00010

Posting a transaction:
> ./scripts/post_txn.sh
>> {"transaction_id": "d0e295f2-c9bf-4e3f-aa2c-2d3ee2050adf"}

Error when posting a transaction (from logs/blockchain.yml):
> tail -f logs/blockchain.log
>> INFO:blockchain.util.crypto:Decoding the digest
>> INFO:blockchain.util.crypto:Performing signature verification
>> INFO:blockchain.util.crypto:Hash validation...
>> INFO:blockchain.util.crypto:Performing stripped hash verification
>> INFO:blockchain.util.crypto:Performing full hash verification
>> ERROR:apscheduler.executors.default:Job "trigger_handler (trigger: cron[second='*/5'], next run at: >> 2017-01-27 11:50:20 CST)" raised an exception
>> Traceback (most recent call last):
>>  File "/Library/Python/2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
>>    retval = job.func(*job.args, **job.kwargs)
>>   File "processing.py", line 149, in trigger_handler
>>    self.notify(event_name=1, current_block_id=get_current_block_id())
>>   File "processing.py", line 112, in notify
>>     observer["callback"](config=observer["config"], **kwargs)
>>   File "processing.py", line 292, in _execute_phase_1
>>     self.network.send_block(self.network.phase_1_broadcast, block_info, phase)
>>   File "/Users/kmocherla/dragonchain/blockchain/network.py", line 413, in send_block
>>     phase_broadcast(block_info, phase_type)
>>   File "/Users/kmocherla/dragonchain/blockchain/network.py", line 420, in phase_1_broadcast
>>     for node in self.peer_dict[phase_type]:
>> KeyError: 2

Any idea on what might be the issue here?

**Comment by micylt** [comment]
@emtech2020 currently nodes must be spun up in descending order (phase 3, 2, 1, etc..). This may be what is causing you issues.

Let me know if this helps.

**Comment by emtech2020** [comment]
Thanks.. unfortunately, that did not help.. We had tried earlier to start phase 2 before starting phase 1 but regardless all phases other than 1, get stuck at the initializing network point.  And of course, if we place a transaction without phase 1, then it is in the "new" status as opposed to in the "approved" status. Let us know if you want us to send anything to help isolate the issue - config file, blockchain.log, starting commands etc.

**Comment by emtech2020** [comment]
These are the steps we tried (in order, config file is posted in the original thread):
> python processing.py --private-key ../pki/sk.pem --public-key ../pki/pk.pem --port 8085 --phase 5
> python processing.py --private-key ../pki/sk.pem --public-key ../pki/pk.pem --port 8084 --phase 4
> python processing.py --private-key ../pki/sk.pem --public-key ../pki/pk.pem --port 8082 --phase 3
> python processing.py --private-key ../pki/sk.pem --public-key ../pki/pk.pem --port 8082 --phase 2
> python processing.py --private-key ../pki/sk.pem --public-key ../pki/pk.pem --port 8081 --phase 1

> python transaction_svc.py --private-key ../pki/sk.pem --public-key ../pki/pk.pem
> python blockchain/query_svc.py --port 8086

Posted a transaction:
> cat valid_payload.json:
>> {
>>   "header": {
>>     "create_ts": 1478382897,
>>     "business_unit": "a3e13076-8683-11e6-97a9-3c970e3bee11",
>>     "family_of_business": "Test Business Family11",
>>     "line_of_business": "My Business11",
>>     "owner": "Test Node1",
>>     "transaction_type": "TT_REQ",
>>     "actor": "c26dd972-8683-11e6-977b-3c970e3bee11",
>>     "entity": "c78f4526-8683-11e6-b1c6-3c970e3bee11"
>>   },
>>   "payload": {
>>     "action": {
>>       "name": "Test Payload1",
>>       "amount": "100.00",
>>       "artifact_id": "23456"
>>     },
>>     "source": "f36c9086-8683-11e6-80dc-3c970e3bee11"
>>   }
>> }

> ./post_txn.sh
>> {"transaction_id": "9c8bc69d-54ee-401c-aaee-e2d79c42deab"}

Log snippet for POST:
> logs/blockchain.log
>> INFO:blockchain.util.crypto:Decoding the digest
>> INFO:blockchain.util.crypto:Performing signature verification
>> INFO:blockchain.util.crypto:Hash validation...
>> INFO:blockchain.util.crypto:Performing stripped hash verification
>> INFO:blockchain.util.crypto:Performing full hash verification
>> ERROR:apscheduler.executors.default:Job "trigger_handler (trigger: cron[second='*/5'], next run at: >> 2017-01-30 11:42:20 CST)" raised an exception
>> Traceback (most recent call last):
>>   File "/Library/Python/2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
>>     retval = job.func(*job.args, **job.kwargs)
>>   File "processing.py", line 149, in trigger_handler
>>     self.notify(event_name=1, current_block_id=get_current_block_id())
>>   File "processing.py", line 112, in notify
>>     observer["callback"](config=observer["config"], **kwargs)
>>   File "processing.py", line 292, in _execute_phase_1
>>     self.network.send_block(self.network.phase_1_broadcast, block_info, phase)
>>   File "/Users/kmocherla/dragonchain/blockchain/network.py", line 421, in send_block
>>     phase_broadcast(block_info, phase_type)
>>   File "/Users/kmocherla/dragonchain/blockchain/network.py", line 428, in phase_1_broadcast
>>     for node in self.peer_dict[phase_type]:
>> KeyError: 2

Please let us know if you need any other info.

**Comment by micylt** [comment]
Hi @emtech2020. I'm sorry that didn't work for you. Let's see what we can do.

Have you created a PostgreSQL database for each phase node?

steps for creating database:
```
cd <Dragonchain Home>/sql
createuser blocky
createdb -O blocky blockchain
```

After this, you will want to create a database for each phase:
```
psql -U blocky -d blockchain -a -f depl.sql
psql -U blocky -d blockchain1 -a -f depl.sql
psql -U blocky -d blockchain2 -a -f depl.sql
psql -U blocky -d blockchain3 -a -f depl.sql
psql -U blocky -d blockchain4 -a -f depl.sql
```

Once you have your databases, you will want to insert the peer nodes into each database using the following database insertion module.
https://github.com/dragonchain/dragonchain/blob/master/blockchain/util/insert_db.py

The process for using this is quite simple.

You will change the arguments of this Node to match what you want to insert.

your first peer:
`node = Node(str(uuid.uuid4()), 'TWDC', 'localhost', '8081', '00010')`

Do make sure you are inserting into the correct database. blockchain1, blockchain2, etc.

After you have adjusted the arguments of the Node, just run insert_db.py. A messaged should be displayed on the console if you have successfully inserted. Check your tables to confirm that you have.

**Comment by TheRoboKitten** [comment]
```Same error: ERROR:apscheduler.executors.default:Job "trigger_handler (trigger: cron[second='*/5'], next run at: 2017-11-18 21:02:40 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "processing.py", line 163, in trigger_handler
    self.notify(event_name=1, current_block_id=get_current_block_id())
  File "processing.py", line 126, in notify
    observer["callback"](config=observer["config"], **kwargs)
  File "processing.py", line 319, in _execute_phase_1
    self.network.public_broadcast(block_info, phase)
  File "/opt/dragonchain/blockchain/network.py", line 712, in public_broadcast
    for node in self.peer_dict[PHASE_5_NODE]:
```

Imported nodes

node phase 4 01111
phase 4 broadcast on

```{"header": {"status": "approved", "family_of_business": "NemoTechnologies", "block_id": 15760131, "line_of_business": "NemoTechnologies", "entity": "NemoTechnologies", "create_ts": 1511038874, "owner": "NemoTechnologies", "creator_id": null, "actor": "NemoTechnologies", "transaction_type": "TT_PROVISION_SSC", "business_unit": "NemoTechnologies", "transaction_id": "8385bbc6-b8df-4946-9d94-f25f35581a76", "transaction_ts": 1511038874}, "payload": {"requirements": ["uuid", "time"], "smart_contract": {"ssc": "ZGVmIGZ1bmMoc2VsZiwgdHJhbnNhY3Rpb24pOiByZXR1cm4gVHJ1ZQ==", "transaction_type": "NemoTechnologies"}, "phase": 2, "version": 1, "criteria": ["phase"], "test": "print 'TEST'"}, "signature": {"stripped_hash": "16ed6b50ae6bc57243106ff2f17563c3a55505309767b0757ca36452a8657f0f50db597d1493b7f82eefcf88e441175a8776062c5769c7aaa349657d5a839d2c", "hash": "c34f57ac0418c0cba92e581c3f738a5cfdb2b346b10d1670a115afb7e35d0fbc6f4871639c4a3b64f8b7f46bddb28c6a7c7d7ae3ff5e455eb418360fcfde1112", "public_key": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwcKqdTqJqL0GdAZTjrqWIjiF2h9I\nqPAtANR+Vmjh8h1l8e5kVPbUHYSKFV4ET0+tUbRWwmX/VjL5RZmEzGTYow==\n-----END PUBLIC KEY-----\n", "signature_ts": 1511038874, "signatory": "transaction-service", "signature": "o5WMDymdPQ76gfGUABensb0mDXs4JI4vMCyJpxmMa6Tl3zx/zk2JMq7e1xQsZEnL+EXc/wz3bLJb\notZYwJqA8w==\n"}}```

**Comment by TheRoboKitten** [comment]
I have phase 5 disabled (I think?) And all nodes are 01111 in config.
Broadcast phase4 turned on?

```Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "processing.py", line 163, in trigger_handler
    self.notify(event_name=1, current_block_id=get_current_block_id())
  File "processing.py", line 126, in notify
    observer["callback"](config=observer["config"], **kwargs)
  File "processing.py", line 319, in _execute_phase_1
    self.network.public_broadcast(block_info, phase)
  File "/opt/dragonchain/blockchain/network.py", line 712, in public_broadcast
    for node in self.peer_dict[PHASE_5_NODE]:```

Still can't figure this out. Is this an acceptable error? My phase 2 trasaction for SSC got accepted. I didn't create separate databases. Don't really have an issue with that right now.
