### ISSUE TITLE
Subscription Response Data Cleanup

### ISSUE THREAD

**Issue by micylt** [dragonchain/dragonchain#96]
Server side responses are not currently being blown away from the sub_vr_transfers_db table under the current implementation of subscription feed.

The response is being built and sent by the subscription_request function under the BlockchainServiceHandler class in the network.py module.

What we would like is for the server to pass back a response with a correlation id attached to it. The client will have to store the correlation id for the sub in the sub_to_db. This value will be updated each time the client receives a response from the subscription node. The client will call with the most recent correlation id on its next call. At which point the server will blow anything away matching that correlation id and respond with everything else.

I think we would like to see backlogs being appropriately cleaned up too.

**Comment by Voxelot** [comment]
We had originally discussed using a max_phase parameter in the subscription criteria to indicate when sufficient verification levels have been reached for that block. However, this does not address concerns subscribing nodes may have for data diversity requirements around that phase. I'm thinking that similar to a correlation id, the client should also pass a completed block id back to the server when it's satisfied with both the phase and diversity requirements for that block. These requirements should be set on a per-subscription basis, as certain subscriptions may require different trusted parties to sign them. If the client requirements are too stringent, the server may forcibly cleanup the backlogs after some configurable amount of time to alleviate back-pressure (although these records are tiny).

This could be stored as another JSON column in the `sub_to_db` table, maybe called `verification_requirements`. For now we could just default it to something like:
```
{
    "phase2": {
        "count": 1
    },
    "phase3": {
        "count": 1
    }
}
```
Starting out this simply specifies how many VR's it needs from each level. However we'll be able to expand the options in the future to maybe include specific taxonomy requirements or node ids. I'm thinking these requirements should be evaluated after receiving a valid `subscription_response`. Store a set of all block ids encountered in the subscription_response and evaluated the requirements for each one. When requirements for a subscription block are satisfied, we'll need to store that completed block id and subscirption id combo somewhere (new table?) to pass along in the next subscription feed request.

**Comment by j0j0r0** [comment]
I'll need to think a bit more on this but, generally, I think that the complete criteria would handle this, and though we were to start with the simple phase level, that we understand make the criteria arbitrarily more complex as needed. 

Also, I think that the VR count may not matter, as if I want level up to level 2, I'll get the first level 2, whereas if I want to know that diversity was achieved, a single level 3 will prove that...

**Comment by Voxelot** [comment]
I was just using VR count as a placeholder, but expanding the current subscription criteria makes sense. 

Also, what if I provisioned a bunch of my own level 2s that connect to my own level 3 with weak/no diversity requirements? I could potentially prevent subscribers from receiving phase 3 verifications from more legitimate sources if we just assume the first level 3 record returned by the network is good enough.

**Comment by j0j0r0** [comment]
Good point.
