### ISSUE TITLE
Smart Contract Expansion

### ISSUE THREAD

**Issue by j0j0r0** [dragonchain/dragonchain#99]
Expand the smart contract (SC) system.

Implementation of the following: 

1. Design for the creation of "reserved" SC - e.g. subscription provisioning, smart contract provisioning, currency operations, marketplace operations, etc. (partially implemented)
1. Design for the structure of the SC dictionary(s) and ability to replace and override
1. Transaction event SC - for approval/denial of individual transactions from within `Transaction Service`
1. Subscription feed based SC - executed against matching _transactions and verification records_ received via subscription.
1. Arbitrary or Library SC - Custom utility code or library code that may be executable from within other SC or by the system at large - e.g. shared user code, currency or marketplace functionality, etc.

*Language extensions should not be considered within this ticket - another ticket shall be created*

**Comment by j0j0r0** [comment]
Currently, I _think_ that the SC may be best separated into separate dictionaries/structures. _Quick thoughts..._

- It _may_ be prudent to separate the reserved SC from the transaction SC so that user configuration would not overwrite the original system function
- The transaction event SC are triggered based solely upon the transaction type, and thus should _probably_ be separated from the subscription SC as they may have duplicate transaction type (not unique in dictionary)
- Subscription SC may have more complex definition to enable a selection criteria (e.g. TT_X + VR3)
- Arbitrary/Library SC will probably have a simple name lookup, but separation

**Comment by j0j0r0** [comment]
Types of SC: 

1. Transaction SC (TSC)
1. Subscription SC (SSC)
1. Library SC (LSC)
1. BroadcastReceipt SC (BSC)

TSC will be divided on implementation to be held in 2 separate structures, one for user/business transactions, and another for reserved transactions.

TSC,  LSC, and BSC will use a simple string key for lookup.
SSC will use composite key of transaction type/name, VR phase, and origin node ID for lookup.

**Comment by j0j0r0** [comment]
We probably need to abstract the divisions between the SC and allow a simple interface.

**Comment by j0j0r0** [comment]
### I/O necessary from within SC

#### TSC

- Transaction in, approve/deny response
- Read only access to blockchain DB table subset

#### SSC

- Access to application DB? (not dragonchain/blockchain DB)
- Network Access?

#### LSC

- Network access?

#### BSC

- Access to application DB? (not dragonchain/blockchain DB)

**Comment by j0j0r0** [comment]
Isolation of the execution of SC is an interesting philosophical question as the business owner will be executing their own code on their own node, and it will have been signed by one or more configured administrative authorities.

There is a chance that the node will be hosted by a third party however, and we will want to do all that we can for best practice isolation of the executed SC code.

**Comment by cheeseandcereal** [comment]
stale
